def rakennukset():
    rakennukset = {
        'Ag': 'Agora',
        'B': 'Kirjasto',
        'D': 'Educa',
        'F': 'Fennicum',
        'FYS1': 'Fysiikan laitosrakennus',
        'FYS2': 'Fysiikan laitosrakennus',
        'FYS3': 'Fysiikan laitosrakennus',
        'FYS4': 'Fysiikan laitosrakennus',
        'FYS5': 'Fysiikan laitosrakennus',
        'Fysiikan': 'Fysiikan laitosrakennus',
        'H': 'Historica',
        'L': 'Liikuntarakennus',
        'L144': 'Liikuntarakennus',
        'L149C': 'Liikuntarakennus',
        'L157': 'Liikuntarakennus',
        'L158': 'Liikuntarakennus',
        'M': 'Musica',
        'MaA': 'Mattilanniemi A',
        'MaD': 'Mattilanniemi D',
        'O': 'Oppio',
        'Oppio': 'Oppio',
        'P': 'Philologica',
        'Philologica': 'Philologica',
        'PiA': 'Philologica',
        'PiB': 'Philologica',
        'S': 'Seminarium',
        'Sauna': 'Fennicum',
        'Seminarium': 'Seminarium',
        'Soveltava': 'Soveltava kemia',
        'Y33': 'Y33',
        'YA': 'Ambiotica',
        'YAA 303': 'Ambiotica',
        'YAA204': 'Ambiotica',
        'YAA305': 'Ambiotica',
        'YAB314': 'Ambiotica',
        'YAB320': 'Ambiotica',
        'YAB322': 'Ambiotica',
        'YAB324': 'Ambiotica',
        'YE': 'Kemian laitosrakennus',
        'YF': 'Kemian laitosrakennus',
        'YFL': 'Fysiikan laitosrakennus',
        'YFL': 'Fysiikan laitosrakennus',
        'YN': 'NanoScience Center',
        'YO': 'Kemian laitosrakennus',
        'Yn': 'NanoScience Center',
        'A': 'Athenaeum'
    }
    return rakennukset


def alueet():
    alueet = {
        'Agora': 'Mattilanniemi',
        'Ambiotica': 'Seminaarinmäki',
        'Athenaeum': 'Seminaarinmäki',
        'Educa': 'Seminaarinmäki',
        'Fennicum': 'Seminaarinmäki',
        'Fysiikan laitosrakennus': 'Ylistönrinne',
        'Historica': 'Seminaarinmäki',
        'Kemian laitosrakennus': 'Ylistönrinne',
        'Kirjasto': 'Seminaarinmäki',
        'Liikuntarakennus': 'Seminaarinmäki',
        'Mattilanniemi A': 'Mattilanniemi',
        'Mattilanniemi D': 'Mattilanniemi',
        'Musica': 'Seminaarinmäki',
        'NanoScience Center': 'Ylistönrinne',
        'Oppio': 'Seminaarinmäki',
        'Philologica': 'Seminaarinmäki',
        'Seminarium': 'Seminaarinmäki',
        'Soveltava kemia': 'Ylistönrinne',
        'Y33': 'Ylistönrinne',
    }
    return alueet
