def rakennukset():
    rakennukset = {
        'A': 'Athenaeum',
        'Ag': 'Agora',
        'Agora': 'Agora',
        'B': 'Kirjasto',
        'D': 'Educa',
        'MaD': 'Mattilanniemi D',
        'MaA': 'Mattilanniemi A',
        'Yn': 'NanoScience Center',
        'Y33': 'Y33',
        'Educa': 'Educa',
        'F': 'Fennicum',
        'YFL': 'Fysiikan laitosrakennus',
        'FYS1': 'Fysiikan laitosrakennus',
        'FYS2': 'Fysiikan laitosrakennus',
        'FYS3': 'Fysiikan laitosrakennus',
        'FYS4': 'Fysiikan laitosrakennus',
        'FYS5': 'Fysiikan laitosrakennus',
        'Fysiikan laitos': 'Fysiikan laitosrakennus',
        'Historica': 'Historica',
        'H': 'Historica',
        'L': 'Liikuntarakennus',
        'L144 EMG-luokka': 'Liikuntarakennus',
        'L149C Videoeditointiluokka': 'Liikuntarakennus',
        'L157 Fysiologian demoluokka': 'Liikuntarakennus',
        'L158 Biomekaniikkan demoluokka': 'Liikuntarakennus',
        'Liikunta': 'Liikuntarakennus',
        'M': 'Musica',
        'Mattilanniemi A': 'Mattilanniemi A',
        'Mattilanniemi D': 'Mattilanniemi D',
        'Musica': 'Musica',
        'Nanoscience Center': 'NanoScience Center',
        'O': 'Oppio',
        'Oppio': 'Oppio',
        'Philologica': 'Philologica',
        'P': 'Philologica',
        'PiA': 'Philologica',
        'PiB': 'Philologica',
        'S': 'Seminarium',
        'Sauna  Fennicum ': 'Fennicum',
        'Sem D': 'Educa',
        'Seminaarinm%C3%A4ki Kirjasto': 'Kirjasto',
        'Seminarium': 'Seminarium',
        'Soveltava kemia': 'Soveltava kemia',
        'YA': 'Ambiotica',
        'YAA 303': 'Ambiotica',
        'YAA204': 'Ambiotica',
        'YAA305': 'Ambiotica',
        'YAB314': 'Ambiotica',
        'YAB320': 'Ambiotica',
        'YAB322': 'Ambiotica',
        'YAB324': 'Ambiotica',
        'YE': 'Kemian laitosrakennus',
        'YF': 'Kemian laitosrakennus',
        'YFL': 'Fysiikan laitosrakennus',
        'YN': 'NanoScience Center',
        'YO': 'Kemian laitosrakennus',
        'sem H': 'Historica'

    }
    return rakennukset
